### ISSUE TITLE
Mobile - banner: Banner text and description should be placed below the banner image so it can be properly displayed.  Also, the banner image should be re-sized to its aspect ratio. 

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Diamond-Edge#56]
Applicable to mobile device from iPad (landscape) resolution and below.

**Comment by roseliesromeo** [comment]
Not totally fixed. Refer to bug #67

**Comment by suniltitan** [comment]
The newly brand logos are in Jpeg format so when we have uploaded they are being displayed completely in white along with the background, so it is better if we can get the transparent logo's of these brands to get it working correctly.
